---
title: "Data for d3 visualizations"
author: "Pamela Inostroza"
date: "10/05/2021"
output: 
  html_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(jsonlite)
```

```{r}
print_json_lines <- function(json, lines) {
  json_lines <- strsplit(json, "\n")[[1]]
  json_lines <- json_lines[lines]
  cat(paste(json_lines, collapse = "\n"))
  invisible(json_lines)
}
```

# World conflicts, development and governance indicators

```{r data}
GovernData <- read.csv("Data/Governance indicators2018-2020.csv")
str(GovernData)
GovernData %>% select(Series.Name, Series.Code) %>% unique()
GovernData <- GovernData %>% filter(!is.na(Time)) %>% mutate(Series.Name = str_remove(Series.Name, ": Estimate")) %>% 
  reshape2::dcast(Country.Name + Country.Code + Series.Code ~ Time, value.var = "Value") %>% 
  mutate(`2020` = `2019`, `2021` = `2019`) %>% 
  reshape2::melt(variable.name = "Time") %>% 
  reshape2::dcast(Country.Name + Country.Code + Time ~ Series.Code, value.var = "value") 

WDIndicData <- read.csv("Data/World development indicators 2018-2020.csv")
str(WDIndicData)
WDIndicData %>% select(Series.Name, Series.Code) %>% unique()
WDIndicData <- WDIndicData %>% filter(!is.na(Time)) %>%  mutate(Series.Name = str_remove(Series.Name, ": Estimate")) %>% 
  reshape2::dcast(Country.Name + Country.Code + Series.Code ~ Time, value.var = "Value") %>% 
  mutate(`2020` = `2019`, `2021` = `2019`) %>% 
  reshape2::melt(variable.name = "Time") %>% 
  reshape2::dcast(Country.Name + Country.Code + Time ~ Series.Code, value.var = "value")

Indicators <- full_join(GovernData, WDIndicData, by = c("Country.Name", "Country.Code", "Time")) %>% 
  mutate(Time = as.numeric(as.character(Time))) 
str(Indicators)

Conflicts <- read.csv("Data/Worldconflicts2018-2021.csv")
str(Conflicts)
ConflictsData <- Conflicts %>% mutate(Gactor1 = case_when(inter1 == 1 ~ "Government or mutinous force",
                                         inter1 == 2 ~ "Rebel force",
                                         inter1 == 3 ~ "Political militia",
                                         inter1 == 4 ~ "Ethnic militia",
                                         inter1 == 5 ~ "Rioters",
                                         inter1 == 6 ~ "Protesters",
                                         inter1 == 7 ~ "Civilians",
                                         inter1 == 8 ~ "Outside/external force"),
                     Gactor2 = case_when(inter2 == 1 ~ "Government or mutinous force",
                                         inter2 == 2 ~ "Rebel force",
                                         inter2 == 3 ~ "Political militia",
                                         inter2 == 4 ~ "Ethnic militia",
                                         inter2 == 5 ~ "Rioters",
                                         inter2 == 6 ~ "Protesters",
                                         inter2 == 7 ~ "Civilians",
                                         inter2 == 8 ~ "Outside/external force"),
                     actor2 = case_when(actor2 == "" ~ "Single actor event",
                                        TRUE ~ actor2),
                     Gactor2 = case_when(Gactor2 == "" ~ "Single actor event",
                                        TRUE ~ Gactor2)) %>% 
  mutate(continent = case_when(region %in% c("South Asia", "Southeast Asia", "East Asia" , 
                                             "Caucasus and Central Asia", "Middle East") ~ "Asia",
                               region %in% c("North America", "South America", "Central America", "Caribbean") ~ "America",
                               region %in% c("Europe") ~ "Europe",
                               region %in% c("Middle Africa", "Eastern Africa", "Southern Africa", 
                                             "Northern Africa", "Western Africa") ~ "Africa" )) %>% 
  
  mutate(source_scale2 = case_when(source_scale %in% c("International", "National-International",
                                                       "Subnational-International",
                                                      "Local partner-International", "Regional-International", 
                                                      "New media-International") ~ "International",
                                  source_scale %in% c("National", "National-Regional", "Other-National",
                                                      "Local partner-National","New media-National") ~ "National",
                                  source_scale %in% c("New media", "Local partner-New media", "Other-New media",
                                                      "New media-Subnational", "New media-Regional") ~ "New media",
                                  source_scale %in% c("Subnational", "Regional", "Other-Subnational", 
                                                      "Subnational-National", "Subnational-Regional", "Local partner-Regional") ~ "Regional",
                                  TRUE ~ "Other")) %>% 
  mutate(region2 = case_when(region == "Europe" & country %in% c("Austria","Belgium","France","Germany","Ireland","Liechtenstein","Luxembourg",
                                            "Monaco","Netherlands","Switzerland","United Kingdom","Vatican City","Bailiwick of Jersey",
                                            "Isle of Man","Bailiwick of Guernsey") ~ "Western Europe",
                             region == "Europe" & country %in% c("Belarus", "Bulgaria", "Czech Republic", "Hungary", "Moldova", "Poland", "Romania", 
                                            "Slovakia",  "Ukraine","Russia","Serbia","Kosovo","Montenegro") ~ "Eastern Europe",
                             region == "Europe" & country %in% c("Estonia", "Latvia", "Lithuania", "Denmark","Finland","Iceland",
                                            "Norway","Sweden","Faroe Islands","Greenland") ~ "Northern Europe",
                             region == "Europe" & country %in% c("Albania", "Andorra", "Bosnia and Herzegovina", "Bulgaria", "Croatia","Cyprus", 
                                            "Greece", "Italy", "Malta", "Portugal", "Romania", "San Marino", "Slovenia", 
                                            "Spain", "North Macedonia", "Yugoslavia","Gibraltar") ~ "Southern Europe",
         TRUE ~ region)) %>% 
  mutate(Motiv = case_when(grepl("coronavirus|pandemic", tolower(notes)) ~ "Covid",
                           grepl("politic", tolower(notes)) ~ "Political",
                           grepl("government|election|activist|leader|payment|authorities|corruption|resignation|price|disobedience|rebellion", 
                                 tolower(notes)) ~ "Government",
                           grepl("teacher|education|student|school", tolower(notes)) ~ "Education",
                           grepl("women|femicide|gender|woman", tolower(notes)) ~ "Women rights",
                           grepl("lgtb|gay|lesbian|same-sex|homophobi", tolower(notes)) ~ "Sexual minorities",
                           grepl("security|murder|violence", tolower(notes)) ~ "Delinquency",
                           grepl("employees|trade union|workers|farm|truck|working|job|employment|agriculture", 
                                 tolower(notes)) ~ "Work",
                           grepl("religious|church|catholic|abortion|jewish|orthodox", tolower(notes)) ~ "Religious",
                           grepl("immigrants|racism|black|asian", tolower(notes)) ~ "Racism",
                           grepl("climate|weather|pollution|nuclear|environment|ecolog", tolower(notes)) ~ "Environment",
                           grepl("health|hospital|sanitary|medical", tolower(notes)) ~ "Health",
                           TRUE ~ "Other"))
ConflictsData %>% filter(year ==2020) %>% 
  group_by(year,Motiv) %>% 
  count()
  
head(ConflictsData)
ConflictsData %>% select(source_scale2,source_scale) %>% unique() %>% arrange(source_scale2)
SummaryConflicts <- ConflictsData %>% group_by(year, continent, region2, iso3, country) %>% 
  summarise(Conflicts = n(),
            Fatalities = sum(fatalities, na.rm = TRUE)) %>% 
  ungroup()  %>% 
  left_join(Indicators, by = c("iso3"="Country.Code", "year"="Time")) %>% 
  group_by(year, continent, region2) %>% 
  mutate(Fatalities2 = Fatalities/ SP.POP.TOTL*100*1000,
         Conflicts2 = Conflicts / sum(Conflicts, na.rm = TRUE) *100) %>% ungroup()
head(SummaryConflicts)
```

## Maps  

```{r}
SummaryConflicts %>% group_by(continent, region2, country) %>% 
  filter(year != 2021) %>% 
  arrange(continent, region2, country) %>% 
  mutate(sumConf = cumsum(Conflicts),
         Diff =  mean(Conflicts/lag(Conflicts),na.rm = TRUE),
         Diff0 = sumConf/lag(sumConf)
         ) %>% 
  select(continent, region2, country, year, Conflicts, sumConf, Diff, Diff0) %>% 
  #filter(Diff0 > 2 & Conflicts > 5000 & sumConf>3000)
  filter(year == 2020) %>% filter(sumConf > 10000)
# case_when(year == 2018 ~ "A",
#                            year == 2019 ~ "B",
#                            year == 2020 ~ "C",
#                            year == 2021 ~ "D")

map1 <- ConflictsData %>% arrange(country) %>% 
  select(country, admin1, latitude, longitude, year, event_type, fatalities) %>% 
  mutate(group = as.character(paste0("y",year)),
         color = event_type) %>% 
  group_by(country, admin1, group, color) %>% 
  summarise(lat = mean(latitude),
            long = mean(longitude),
            fatalities = sum(fatalities),
            conflicts = n())

mapAFG <- map1  %>% 
  filter(country == "Afghanistan") %>% 
  select(-conflicts) %>% 
  rename(size = fatalities) %>% 
  select(country, admin1, long, lat, group, color,size) %>% 
  group_by(country) %>% 
  select(-admin1) %>% 
  tidyr::nest() 

Dmap1AFG <- jsonlite::toJSON(mapAFG, pretty = TRUE)
print_json_lines(jsonlite::toJSON(mapAFG, pretty = TRUE), 1:30)

validate(Dmap1AFG)
write(prettify(Dmap1AFG), file = "Data/forvis/AFG1.json")


mapAFG2 <- map1  %>% 
  filter(country == "Afghanistan") %>% 
  select(-fatalities) %>% 
  rename(size = conflicts) %>% 
  select(country, admin1, long, lat, group, size) %>% 
  group_by(country) %>% 
  select(-admin1) %>% 
  tidyr::nest() 

Dmap1AFG2 <- jsonlite::toJSON(mapAFG2, pretty = TRUE)
print_json_lines(jsonlite::toJSON(mapAFG2, pretty = TRUE), 1:30)

validate(Dmap1AFG2)
write(prettify(Dmap1AFG), file = "Data/forvis/AFG2.json")




mapPAL1 <- map1  %>% 
  filter(country %in% c("Palestine")) %>% 
  rename(size = conflicts) %>% 
  select(country, admin1, long, lat, group, color, size, fatalities) %>% 
  group_by(country) %>% 
  tidyr::nest() 

Dmap1PAL1 <- jsonlite::toJSON(mapPAL1, pretty = TRUE)
print_json_lines(jsonlite::toJSON(mapPAL1, pretty = TRUE), 1:30)

validate(Dmap1PAL1)
write(prettify(Dmap1PAL1), file = "Data/forvis/PAL1.json")

mapISR2 <- map1  %>% 
  filter(country %in% c("Israel")) %>% 
  rename(size = conflicts) %>% 
  select(country, admin1, long, lat, group, color, size, fatalities) %>% 
  group_by(country) %>% 
  tidyr::nest() 

Dmap1ISR2 <- jsonlite::toJSON(mapISR2, pretty = TRUE)
print_json_lines(jsonlite::toJSON(mapISR2, pretty = TRUE), 1:30)

validate(Dmap1ISR2)
write(prettify(Dmap1ISR2), file = "Data/forvis/ISR1.json")
```

## Parallel coordinates

```{r }
SummaryConflictsMean <- SummaryConflicts  %>%
  group_by(year, continent) %>% 
  summarise_if(is.numeric, mean, na.rm = TRUE)

cor <- cor(SummaryConflicts[-c(1:5,8),-c(1:5,8)], use = "pairwise.complete.obs")
cor[1:2,]



# For parallel coordinates
Ind <- c("Fatalities2", "Conflicts2", "IT.NET.USER.ZS", "IT.CEL.SETS", "ST.INT.ARVL","ST.INT.DPRT", "SH.DYN.MORT", "SP.POP.GROW")
ParallelCoordinatesVis1 <- SummaryConflicts   %>% 
  select(year, continent, region2, country, all_of(Ind)) %>% 
  arrange(year, continent, region2) %>% 
  mutate(IT.CEL.SETS = IT.CEL.SETS/10000000,
         ST.INT.ARVL = ST.INT.ARVL/10000000,
         ST.INT.DPRT = ST.INT.DPRT/10000000) %>% 
  group_by(year, continent, region2) %>% 
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  mutate_if(is.numeric, round, 1) %>% 
  mutate_if(~any(is.na(.)),~if_else(is.na(.),0,.)) %>% 
  rename(region = region2,
         `Conflicts (Average % of country participation in the region)` = Conflicts2,
         `Fatalities (Average % of country population per 1000)` = Fatalities2,
         `Individuals using the Internet (Mean % of population)` = IT.NET.USER.ZS, 
  `Mobile cellular subscriptions (Mean per 10 million)` = IT.CEL.SETS, 
  `International tourism, number of arrivals (Mean per 10 million)` = ST.INT.ARVL,
  `International tourism, number of departures (Mean per 10 million)` = ST.INT.DPRT, 
  `Mortality rate, under-5 (Mean per 1,000 live births)` = SH.DYN.MORT, 
  `Population growth (Mean annual %)` = SP.POP.GROW
  )

#write.csv(ParallelCoordinatesVis1, file = "Data/forvis/ParallelCoordinates2.csv", na = "")

ParallelCoordinatesVis2 <-  SummaryConflicts %>% 
  select(year, continent, region2, country, Fatalities, Conflicts, 
         CC.EST, GE.EST, PV.EST, RL.EST, RQ.EST, VA.EST
         ) %>% 
  group_by(year, continent, region2) %>% 
  summarise(Fatalities= sum(Fatalities),
            Conflicts = sum(Conflicts),
            CC.EST = mean(CC.EST, na.rm = TRUE),
            GE.EST = mean(GE.EST,na.rm = TRUE),
            PV.EST = mean(PV.EST,na.rm = TRUE),
            RL.EST = mean(RL.EST,na.rm = TRUE),
            RQ.EST = mean(RQ.EST,na.rm = TRUE),
            VA.EST = mean(VA.EST,na.rm = TRUE)) %>%
  arrange() %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(Fatalities= Fatalities/sum(Fatalities, na.rm = TRUE)*100,
         Conflicts = Conflicts/sum(Conflicts, na.rm = TRUE)*100) %>% 
  ungroup() %>% 
  mutate_if(is.numeric, round, 1) %>% 
  rename(region = region2,
         `Conflicts (% of total)` = Conflicts,
         `Fatalities (% of total)` = Fatalities,
         `Control of Corruption (Mean)` = CC.EST, 
         `Government Effectiveness (Mean)` = GE.EST, 
         `Political Stability and Absence of Violence/Terrorism (Mean)` = PV.EST, 
         `Rule of Law (Mean)` = RL.EST, 
         `Regulatory Quality (Mean)` = RQ.EST, 
         `Voice and Accountability (Mean)` = VA.EST)

#write.csv(ParallelCoordinatesVis2, file = "Data/forvis/ParallelCoordinates1.csv", na = "")


ParallelCoordinatesVis <- full_join(ParallelCoordinatesVis1,ParallelCoordinatesVis2, by = c("year", "continent","region")) 
write.csv(ParallelCoordinatesVis, file = "Data/forvis/ParallelCoordinates.csv", na = "")

```

## Sunburst 

```{r}

ToJsonData1 <- ConflictsData %>% 
  select(year,  event_type, sub_event_type, country, fatalities) %>% 
  group_by(year, event_type, sub_event_type, country) %>% 
  summarise(fatalities = sum(fatalities, na.rm = TRUE),
            conflicts = n()) %>% ungroup() %>% 
  group_by(year) %>% 
  mutate(fatalities = fatalities/sum(fatalities, na.rm = TRUE),
         conflicts = conflicts/sum(conflicts, na.rm = TRUE)) %>% ungroup()

sunburst1 <- ToJsonData1 %>% 
  select(year, event_type, sub_event_type, country, fatalities) %>%
  group_by(year, event_type, sub_event_type) %>%
  tidyr::nest() %>%
  rename(name = sub_event_type, 
    children = data) %>%
  group_by(year, event_type) %>% 
  tidyr::nest() %>% 
  rename(name = event_type, 
    children = data) %>% 
  group_by(year) %>% 
  tidyr::nest() %>% 
  rename(name = year, 
    children = data) %>% 
  mutate(conf = "Conflicts") %>% 
  group_by(conf) %>% 
  tidyr::nest() %>% 
  rename(name = conf, children = data)

Dsunburst1 <- jsonlite::toJSON(sunburst1, pretty = TRUE)
print_json_lines(jsonlite::toJSON(sunburst1, pretty = TRUE), 1:30)

validate(Dsunburst1)
write(prettify(Dsunburst1), file = "Data/forvis/Sunburst2.json")

sunburst2<- ToJsonData1 %>% 
  select(year, event_type, sub_event_type, country,conflicts) %>%
  group_by(year, event_type, sub_event_type) %>%
  tidyr::nest() %>%
  rename(name = sub_event_type, 
    children = data) %>%
  group_by(year, event_type) %>% 
  tidyr::nest() %>% 
  rename(name = event_type, 
    children = data) %>% 
  group_by(year) %>% 
  tidyr::nest() %>% 
  rename(name = year, 
    children = data) %>% 
  mutate(conf = "Conflicts") %>% 
  group_by(conf) %>% 
  tidyr::nest() %>% 
  rename(name = conf, children = data)


# ToJsonData2 <- ConflictsData %>% 
#   arrange(country, event_date) %>% 
#   select(year, source_scale2,  sub_event_type) %>% 
#   group_by(year, source_scale2, sub_event_type) %>% 
#   summarise(valor = n()) %>% ungroup() %>% 
#   group_by(year) %>% 
#   mutate(valor = valor/ sum(valor))

# 
# sunburst2 <- ToJsonData2 %>% 
#   rename(name1 = sub_event_type) %>% 
#   group_by(year, source_scale2) %>%
#   tidyr::nest() %>% 
#   rename(name = source_scale2, 
#     children = data) %>% 
#   group_by(year) %>% 
#   tidyr::nest() %>% 
#   rename(name = year, 
#     children = data) %>% 
#   mutate(conf = "Conflicts") %>% 
#   group_by(conf) %>% 
#   tidyr::nest() %>% 
#   rename(name = conf, children = data)

Dsunburst2 <- jsonlite::toJSON(sunburst2, pretty = TRUE)
print_json_lines(jsonlite::toJSON(sunburst2, pretty = TRUE), 1:30)

validate(Dsunburst2)
write(prettify(Dsunburst2), file = "Data/forvis/Sunburst1.json")

```

## Zoom sunburst/bubble

```{r}
ToJsonData3 <- ConflictsData %>% 
  select(year, event_type, sub_event_type, Motiv, region2) %>% 
  group_by(year, event_type, sub_event_type, Motiv, region2) %>% 
  count(name = "value") %>% ungroup()

zoom1 <- ToJsonData3 %>% 
  group_by(year, event_type, sub_event_type, Motiv, region2) %>%
  summarise(value = sum(value)) %>% 
  rename(name = region2) %>% 
  group_by(year, event_type, sub_event_type, Motiv) %>%
  tidyr::nest() %>%
  rename(name = Motiv,
         children = data) %>%
   group_by(year,event_type, sub_event_type) %>%
  tidyr::nest() %>%
  rename(name = sub_event_type,
         children = data) %>% filter(year == 2020 & event_type == "Protests") %>% ungroup() %>% select(-year, -event_type) %>% 
  mutate(conf = "Conflicts") %>% 
  group_by(conf) %>% 
  tidyr::nest() %>% 
  rename(name = conf, children = data)

Dzoom1 <- jsonlite::toJSON(zoom1, pretty = TRUE)
print_json_lines(jsonlite::toJSON(zoom1, pretty = TRUE), 1:30)

validate(Dzoom1)
write(prettify(Dzoom1), file = "Data/forvis/ZoomSunburst1.json")
```

```{r}
ToJsonData3 <- ConflictsData %>% 
  group_by(event_type, sub_event_type, region2) %>% 
  count(name = "value") %>% ungroup()

bubble1 <- ToJsonData3 %>% 
  select(event_type,sub_event_type, region2, value) %>% 
  group_by(event_type,sub_event_type, region2) %>%
  summarise(size = sum(value)) %>% 
  rename(name = region2) %>% 
  group_by(event_type,sub_event_type) %>%
  tidyr::nest() %>%
  rename(name=sub_event_type,
         children = data) %>%
  group_by(event_type) %>%
  tidyr::nest() %>%
  rename(name=event_type,
         children = data) %>% 
  mutate(conf = "Conflicts") %>% 
  group_by(conf) %>% 
  tidyr::nest() %>% 
  rename(name = conf, children = data)

Dbubble1 <- jsonlite::toJSON(bubble1, pretty = TRUE)
print_json_lines(jsonlite::toJSON(bubble1, pretty = TRUE), 1:30)

validate(Dbubble1)
write(prettify(Dbubble1), file = "Data/forvis/Bubble1.json")
```

```{r}

ToJsonData4 <- ConflictsData %>% 
  mutate(event_month = lubridate::month(lubridate::dmy(event_date))) %>% 
  select(event_month, year, event_type) %>% 
  group_by(event_month, year, event_type) %>% 
  count(name = "value") %>% ungroup()

zoom2 <- ToJsonData4 %>%
  mutate(year = as.character(year),
         event_month = as.character(event_month)) %>% 
  group_by(event_month,year) %>%
  rename(name = event_type) %>% 
  tidyr::nest() %>%
  rename(name = year, 
         children = data) %>% 
  group_by(event_month) %>% 
  tidyr::nest() %>% 
  rename(name = event_month, 
         children = data) %>% 
  # group_by(event_type) %>% 
  # tidyr::nest() %>% 
  # rename(name = event_type, 
  #        children = data) %>% 
  mutate(conf = "Conflicts") %>% 
  group_by(conf) %>% 
  tidyr::nest() %>% 
  rename(name = conf, children = data)


Dzoom2 <- jsonlite::toJSON(zoom2, pretty = TRUE)
print_json_lines(jsonlite::toJSON(zoom2, pretty = TRUE), 1:30)

validate(Dzoom2)
write(prettify(Dzoom2), file = "Data/forvis/ZoomSunburst2.json")
```

## Spider  

```{r}
spider2 <- ConflictsData %>% filter(year == 2020)  %>% 
  group_by(event_type, continent) %>% 
  summarise(value = sum(fatalities))  %>% 
  mutate(value = value / sum(value)) %>%
  rename(axis = event_type) %>% 
  group_by(continent) %>% 
  tidyr::nest() %>% ungroup() %>% select(-continent) 

Dspider2 <- jsonlite::toJSON(spider2, pretty = TRUE)
print_json_lines(jsonlite::toJSON(spider2, pretty = TRUE), 1:30)

validate(Dspider2)
write(prettify(Dspider2), file = "Data/forvis/Spider2.json")

##2
spider3 <- ConflictsData %>% filter(year == 2020)  %>% 
  group_by(continent,event_type) %>% 
  summarise(value = sum(fatalities))  %>% 
  mutate(value = value / sum(value)) %>%
  rename(className = continent,
         axis = event_type) %>% 
  group_by(className) %>% 
  tidyr::nest()

Dspider3 <- jsonlite::toJSON(spider3, pretty = TRUE)
print_json_lines(jsonlite::toJSON(spider3, pretty = TRUE), 1:30)

validate(Dspider3)
write(prettify(Dspider3), file = "Data/forvis/Spider3.json")



##4
fspider4 <- ConflictsData %>% 
  group_by(country, event_type, Gactor1) %>% 
  summarise(fatalities = sum(fatalities),
            conflicts = n()) %>% 
  mutate(government = case_when(Gactor1 %in% c("Government or mutinous force") ~ conflicts),
         rebelforce = case_when(Gactor1 == "Rebel force" ~ conflicts)) %>% 
  group_by(country, event_type) %>% 
  summarise(fatalities = sum(fatalities),
            conflicts = sum(conflicts),
            government = max(government, na.rm = TRUE),
            rebelforce = ifelse(max(rebelforce, na.rm = TRUE) == -Inf, 0, max(rebelforce, na.rm = TRUE))) %>% 
  mutate(battles = case_when(event_type %in% c("Battles") ~ conflicts),
         protest = case_when(event_type == "Protests" ~ conflicts)) %>% 
  group_by(country) %>% 
  summarise(fatalities = sum(fatalities),
            conflicts = sum(conflicts),
            battles = max(battles, na.rm = TRUE),
            protests = max(protest, na.rm = TRUE),
            government = max(government, na.rm = TRUE),
            rebelforce = ifelse(max(rebelforce, na.rm = TRUE) == -Inf, 0, max(rebelforce, na.rm = TRUE)))


fspider4 %>% 
  filter(fatalities > 50000 | conflicts > 10000 | protests >5000) %>% print(n=Inf)

spider4 <- fspider4 %>% filter(country %in% c("Afghanistan", "Syria", "United States", "India", "Ukraine")) %>% 
  reshape2::melt() %>% 
  group_by(variable) %>% 
  mutate(value = value / sum(value)) %>%
  rename(className = country,
         axis = variable) %>% ungroup() %>% 
  group_by(className) %>% 
  tidyr::nest() %>% ungroup() %>% select(-className)

Dspider4 <- jsonlite::toJSON(spider4, pretty = TRUE)
print_json_lines(jsonlite::toJSON(spider4, pretty = TRUE), 1:30)

validate(Dspider4)
write(prettify(Dspider4), file = "Data/forvis/Spider4.json")
```

## Map 

```{r}
map <- ConflictsData %>% 
  select(country, longitude, latitude, event_type) %>% 
  group_by(country, longitude, latitude, event_type) %>% 
  count() %>% 
  rename(long = longitude,
         lat = latitude)

data8 <- jsonlite::toJSON(map, pretty = TRUE)
print_json_lines(jsonlite::toJSON(map, pretty = TRUE), 1:30)

validate(data8)
write(prettify(data8), file = "Data/forvis/map1.json")
```

## Dependency chord diagram

```{r}
ToJsonData5 <- ConflictsData %>% filter(year == 2020) %>% 
  select(country, Gactor1, Gactor2) %>% 
  mutate(Gactor2 = ifelse(is.na(Gactor2), "Single actor", Gactor2), 
         name = paste0(paste0(paste0("Conflicts.", Gactor1),"."),gsub("\\.","",gsub(",","",gsub(" ","",country)))), 
         Gactor2 = paste0(paste0(paste0("Conflicts.", Gactor2),"."),gsub("\\.","",gsub(",","",gsub(" ","",country))))) %>% 
  group_by(name, Gactor2) %>% 
  summarise(size = n()) %>% 
  group_by(name) %>% 
  summarise(size = sum(size),
    imports = list(Gactor2)) %>% 
  ungroup() %>% 
  select(name, size, imports)
  

data5 <- jsonlite::toJSON(ToJsonData5, pretty = TRUE)
print_json_lines(jsonlite::toJSON(ToJsonData5, pretty = TRUE), 1:30)


validate(data5)
write(prettify(data5), file = "Data/forvis/DependencyDiagram2.json")
```

## Multiple categories chord diagram
```{r}
ToJsonDataMC <- ConflictsData %>% 
  arrange(year, Gactor1, Gactor2, region2) %>%
  group_by(year, Gactor1, Gactor2, region2) %>%
  mutate(Gactor2 = ifelse(is.na(Gactor2), "Single Actor", Gactor2)) %>%
  summarise(#fatalities = sum(fatalities),
            conflicts = n()
            ) %>%
  mutate(#fatalities = ifelse(is.na(fatalities), 0, fatalities),
         conflicts = ifelse(is.na(conflicts), 0, conflicts)
         ) %>%
  reshape2::dcast(year  + Gactor1 + Gactor2~ region2) %>%
  reshape2::melt(id.vars = c("year", "Gactor1","Gactor2"), variable.name = "region2") %>%
  mutate(value = ifelse(is.na(value), 0, value)) %>%
  reshape2::dcast(year + Gactor1 + region2 ~ Gactor2) %>%
  mutate(`Single Actor` = 0) %>% replace(is.na(.), 0)

dataforJson <- ToJsonDataMC %>% 
  group_by(year , Gactor1) %>%
  summarise(delete = list(Civilians),
            delete1= list(`Ethnic militia`),
            delete2= list(`Government or mutinous force`),
            delete3= list(`Outside/external force`),
            delete4= list(`Political militia`),
            delete5= list(`Protesters`),
            delete6= list(`Rebel force`),
            delete7= list(`Rioters`),
            delete8= list(`Single Actor`)) %>% 
  select(-Gactor1) %>% ungroup()

#2018
dataforJson18 <- dataforJson %>% filter(year == 2018) %>% select(-year)

name<- colnames(ToJsonDataMC %>% filter(year == 2018))[!colnames(ToJsonDataMC %>% filter(year == 2018)) %in% c("year","Gactor1","region2")]
color <- c("#4e79a7","#59a14f","#9c755f","#f28e2b","#edc948","#bab0ac","#e15759","#b07aa1","#76b7b2")#,"#ff9da7")
nodes = data.frame(name, color) %>% tidyr::nest(data = everything()) %>% rename(nodes = data) %>% jsonlite::toJSON()

categories <- ToJsonDataMC %>% filter(year == 2018) %>% select(region2) %>% unique() %>% as.data.frame() %>% 
  rename(name = region2) %>% tidyr::nest(data = everything()) %>% rename(categories=data) %>% jsonlite::toJSON()

links18 = dataforJson18 %>% tidyr::nest(data = everything()) %>% rename(links = data) %>% jsonlite::toJSON(pretty = TRUE)

print_json_lines(jsonlite::toJSON(links18, pretty = TRUE), 1:30)
validate(links18)
write(prettify(links), file = "Data/forvis/MultipleCatChordDiag18.json")

#2019
dataforJson19 <- dataforJson %>% filter(year == 2019) %>% select(-year)

name<- colnames(ToJsonDataMC %>% filter(year == 2019))[!colnames(ToJsonDataMC %>% filter(year == 2019)) %in% c("year","Gactor1","region2")]
color <- c("#4e79a7","#59a14f","#9c755f","#f28e2b","#edc948","#bab0ac","#e15759","#b07aa1","#76b7b2")#,"#ff9da7")
nodes = data.frame(name, color) %>% tidyr::nest(data = everything()) %>% rename(nodes = data) %>% jsonlite::toJSON()

categories <- ToJsonDataMC %>% filter(year == 2019) %>% select(region2) %>% unique() %>% as.data.frame() %>% 
  rename(name = region2) %>% tidyr::nest(data = everything()) %>% rename(categories=data) %>% jsonlite::toJSON()

links19 = dataforJson19 %>% tidyr::nest(data = everything()) %>% rename(links = data) %>% jsonlite::toJSON(pretty = TRUE)

print_json_lines(jsonlite::toJSON(links19, pretty = TRUE), 1:30)
validate(links19)
write(prettify(links19), file = "Data/forvis/MultipleCatChordDiag19.json")

#2020
dataforJson20 <- dataforJson %>% filter(year == 2020) %>% select(-year)

name<- colnames(ToJsonDataMC %>% filter(year == 2020))[!colnames(ToJsonDataMC %>% filter(year == 2020)) %in% c("year","Gactor1","region2")]
color <- c("#4e79a7","#59a14f","#9c755f","#f28e2b","#edc948","#bab0ac","#e15759","#b07aa1","#76b7b2")#,"#ff9da7")
nodes = data.frame(name, color) %>% tidyr::nest(data = everything()) %>% rename(nodes = data) %>% jsonlite::toJSON()

categories <- ToJsonDataMC %>% filter(year == 2020) %>% select(region2) %>% unique() %>% as.data.frame() %>% 
  rename(name = region2) %>% tidyr::nest(data = everything()) %>% rename(categories=data) %>% jsonlite::toJSON()

links20 = dataforJson20 %>% tidyr::nest(data = everything()) %>% rename(links = data) %>% jsonlite::toJSON(pretty = TRUE)

print_json_lines(jsonlite::toJSON(links20, pretty = TRUE), 1:30)
validate(links20)
write(prettify(links20), file = "Data/forvis/MultipleCatChordDiag20.json")

#2021
dataforJson21 <- dataforJson %>% filter(year == 2021) %>% select(-year)

name<- colnames(ToJsonDataMC %>% filter(year == 2021))[!colnames(ToJsonDataMC %>% filter(year == 2021)) %in% c("year","Gactor1","region2")]
color <- c("#4e79a7","#59a14f","#9c755f","#f28e2b","#edc948","#bab0ac","#e15759","#b07aa1","#76b7b2")#,"#ff9da7")
nodes = data.frame(name, color) %>% tidyr::nest(data = everything()) %>% rename(nodes = data) %>% jsonlite::toJSON()

categories <- ToJsonDataMC %>% filter(year == 2021) %>% select(region2) %>% unique() %>% as.data.frame() %>% 
  rename(name = region2) %>% tidyr::nest(data = everything()) %>% rename(categories=data) %>% jsonlite::toJSON()

links21 = dataforJson21 %>% tidyr::nest(data = everything()) %>% rename(links = data) %>% jsonlite::toJSON(pretty = TRUE)

print_json_lines(jsonlite::toJSON(links21, pretty = TRUE), 1:30)
validate(links21)
write(prettify(links21), file = "Data/forvis/MultipleCatChordDiag21.json")
```